Update shell completions

diff --git a/.bash.d/bash-completion/completions/make b/.bash.d/bash-completion/completions/make
--- a/.bash.d/bash-completion/completions/make
+++ b/.bash.d/bash-completion/completions/make
@@ -1,78 +1,244 @@
-# bash completion for GNU make
+# bash completion for GNU make                             -*- shell-script -*-
 
-have make || have gmake || have gnumake || have pmake &&
+_make_target_extract_script()
+{
+    local mode="$1"
+    shift
+
+    local prefix="$1"
+    local prefix_pat=$(command sed 's/[][\,.*^$(){}?+|/]/\\&/g' <<<"$prefix")
+    local basename=${prefix##*/}
+    local dirname_len=$((${#prefix} - ${#basename}))
+    # Avoid expressions like '\(.\{0\}\)', FreeBSD sed doesn't like them:
+    # > sed: 1: ...: RE error: empty (sub)expression
+    local dirname_re=
+    ((dirname_len > 0)) && dirname_re="\(.\{${dirname_len}\}\)"
+
+    if [[ ! $dirname_re ]]; then
+        local output="\1"
+    elif [[ $mode == -d ]]; then
+        # display mode, only output current path component to the next slash
+        local output="\2"
+    else
+        # completion mode, output full path to the next slash
+        local output="\1\2"
+    fi
+
+    cat <<EOF
+    1,/^# * Make data base/           d;        # skip any makefile output
+    /^# * Finished Make data base/,/^# * Make data base/{
+                                      d;        # skip any makefile output
+    }
+    /^# * Variables/,/^# * Files/     d;        # skip until files section
+    /^# * Not a target/,/^$/          d;        # skip not target blocks
+    /^${prefix_pat}/,/^$/!            d;        # skip anything user dont want
+
+    # The stuff above here describes lines that are not
+    #  explicit targets or not targets other than special ones
+    # The stuff below here decides whether an explicit target
+    #  should be output.
+
+    /^# * File is an intermediate prerequisite/ {
+      s/^.*$//;x;                               # unhold target
+      d;                                        # delete line
+    }
+
+    /^$/ {                                      # end of target block
+      x;                                        # unhold target
+      /^$/d;                                    # dont print blanks
+      s|^${dirname_re-}\(.\{${#basename}\}[^:]*\):.*$|${output}|p;
+      d;                                        # hide any bugs
+    }
+
+    # This pattern includes a literal tab character as \t is not a portable
+    # representation and fails with BSD sed
+    /^[^#	:%]\{1,\}:/ {         # found target block
+      /^\.PHONY:/                 d;            # special target
+      /^\.SUFFIXES:/              d;            # special target
+      /^\.DEFAULT:/               d;            # special target
+      /^\.PRECIOUS:/              d;            # special target
+      /^\.INTERMEDIATE:/          d;            # special target
+      /^\.SECONDARY:/             d;            # special target
+      /^\.SECONDEXPANSION:/       d;            # special target
+      /^\.DELETE_ON_ERROR:/       d;            # special target
+      /^\.IGNORE:/                d;            # special target
+      /^\.LOW_RESOLUTION_TIME:/   d;            # special target
+      /^\.SILENT:/                d;            # special target
+      /^\.EXPORT_ALL_VARIABLES:/  d;            # special target
+      /^\.NOTPARALLEL:/           d;            # special target
+      /^\.ONESHELL:/              d;            # special target
+      /^\.POSIX:/                 d;            # special target
+      /^\.NOEXPORT:/              d;            # special target
+      /^\.MAKE:/                  d;            # special target
+EOF
+
+    # don't complete with hidden targets unless we are doing a partial completion
+    if [[ ! ${prefix_pat} || ${prefix_pat} == */ ]]; then
+        cat <<EOF
+      /^${prefix_pat}[^a-zA-Z0-9]/d;            # convention for hidden tgt
+EOF
+    fi
+
+    cat <<EOF
+      h;                                        # hold target
+      d;                                        # delete line
+    }
+
+EOF
+}
+
+# Truncate the non-unique filepaths in COMPRELY to only generate unique
+# directories or files.  This function discards the files under subdirectories
+# unless the path is unique under each subdirectory and instead generate the
+# subdirectory path.  For example, when there are two candidates, "abc/def" and
+# "abc/xyz", we generate "abc/" instead of generating both candidates directly.
+# When there is only one candidate "abc/def", we generate the full path
+# "abc/def".
+#
+# @var[in] cur
+# @var[in] mode
+# @var[in,out] COMPREPLY
+_comp_make__truncate_non_unique_paths()
+{
+    local prefix=$cur
+    [[ $mode == -d ]] && prefix=
+    if ((${#COMPREPLY[@]} > 0)); then
+        # collect the possible completions including the directory names in
+        # `paths' and count the number of children of each subdirectory in
+        # `nchild'.
+        local -A paths nchild
+        local target
+        for target in "${COMPREPLY[@]}"; do
+            local path=${target%/}
+            while [[ ! ${paths[$path]+set} ]] &&
+                paths[$path]=set &&
+                [[ $path == "$prefix"*/* ]]; do
+                path=${path%/*}
+                nchild[$path]=$((${nchild[$path]-0} + 1))
+            done
+        done
+
+        COMPREPLY=()
+        local nreply=0
+        for target in "${!paths[@]}"; do
+            # generate only the paths that do not have a unique child and whose
+            # all parent and ancestor directories have a unique child.
+            ((${nchild[$target]-0} == 1)) && continue
+            local path=$target
+            while [[ $path == "$prefix"*/* ]]; do
+                path=${path%/*}
+                ((${nchild[$path]-0} == 1)) || continue 2
+            done
+
+            # suffix `/' when the target path is a subdiretory, which has
+            # at least one child.
+            COMPREPLY[nreply++]=$target${nchild[$target]+/}
+        done
+    fi
+}
+
 _make()
 {
-    local file makef makef_dir="." makef_inc cur prev i split=false
+    local cur prev words cword split comp_args
+    _comp_initialize -s -- "$@" || return
 
-    COMPREPLY=()
-    _get_comp_words_by_ref cur prev
+    local makef makef_dir=("-C" ".") i
 
-    _split_longopt && split=true
-
+    local noargopts='!(-*|*[foWICmEDVxj]*)'
+    # shellcheck disable=SC2254
     case $prev in
-        -f|-o|-W|--file|--makefile|--old-file|--new-file|--assume-old|--assume-new|--what-if)
+        --file | --makefile | --old-file | --assume-old | --what-if | --new-file | \
+            --assume-new | -${noargopts}[foW])
             _filedir
-            return 0
+            return
             ;;
-        -I|-C|--directory|--include-dir)
+        --include-dir | --directory | -${noargopts}[ICm])
             _filedir -d
-            return 0
+            return
+            ;;
+        -${noargopts}E)
+            COMPREPLY=($(compgen -v -- "$cur"))
+            return
+            ;;
+        --eval | -${noargopts}[DVx])
+            return
+            ;;
+        --jobs | -${noargopts}j)
+            COMPREPLY=($(compgen -W "{1..$(($(_ncpus) * 2))}" -- "$cur"))
+            return
             ;;
     esac
 
-    $split && return 0
+    $split && return
 
-    if [[ "$cur" == -* ]]; then
-        COMPREPLY=( $( compgen -W '-b -m -B -C -d -e -f -h -i -I\
-            -j -l -k -n -o -p -q -r -R - s -S -t -v -w -W \
-            --always-make --directory --debug \
-            --environment-overrides --file --makefile --help \
-            --ignore-errors --include-dir --jobs --load-average \
-            --max-load --keep-going --just-print --dry-run \
-            --recon --old-file --assume-old --print-data-base \
-            --question --no-builtin-rules --no-builtin-variables \
-            --silent --quiet --no-keep-goind --stop --touch \
-            --version --print-directory --no-print-directory \
-            --what-if --new-file --assume-new \
-            --warn-undefined-variables' -- "$cur" ) )
+    if [[ $cur == -* ]]; then
+        COMPREPLY=($(
+            compgen -W '$(_parse_help "$1" || _parse_usage "$1")' -- "$cur"
+        ))
+        [[ ${COMPREPLY-} == *= ]] && compopt -o nospace
+    elif [[ $cur == *=* ]]; then
+        prev=${cur%%=*}
+        cur=${cur#*=}
+        local diropt
+        [[ ${prev,,} == *dir?(ectory) ]] && diropt=-d
+        _filedir $diropt
     else
         # before we check for makefiles, see if a path was specified
         # with -C/--directory
-        for (( i=0; i < ${#COMP_WORDS[@]}; i++ )); do
-            if [[ ${COMP_WORDS[i]} == -@(C|-directory) ]]; then
-                # eval for tilde expansion
-                eval makef_dir=${COMP_WORDS[i+1]}
+        for ((i = 1; i < ${#words[@]}; i++)); do
+            if [[ ${words[i]} == -@(C|-directory) ]]; then
+                # Expand tilde expansion
+                local ret
+                _comp_dequote "${words[i + 1]-}" &&
+                    [[ -d ${ret-} ]] &&
+                    makef_dir=(-C "$ret")
                 break
             fi
         done
 
         # before we scan for targets, see if a Makefile name was
         # specified with -f/--file/--makefile
-        for (( i=0; i < ${#COMP_WORDS[@]}; i++ )); do
-            if [[ ${COMP_WORDS[i]} == -@(f|-?(make)file) ]]; then
-                # eval for tilde expansion
-                eval makef=${COMP_WORDS[i+1]}
+        for ((i = 1; i < ${#words[@]}; i++)); do
+            if [[ ${words[i]} == -@(f|-?(make)file) ]]; then
+                # Expand tilde expansion
+                local ret
+                _comp_dequote "${words[i + 1]-}" &&
+                    [[ -f ${ret-} ]] &&
+                    makef=(-f "$ret")
                 break
             fi
         done
 
-        [ -n "$makef" ] && makef="-f ${makef}"
-        [ -n "$makef_dir" ] && makef_dir="-C ${makef_dir}"
+        # recognise that possible completions are only going to be displayed so
+        # only the base name is shown.
+        #
+        # Note: This is currently turned off because the test suite of
+        # bash-completion conflicts with it; it uses "set show-all-if-ambiguous
+        # on" (causing COMP_TYPE == 37) to retrieve the action completion
+        # results, and also the compact form with only the basenames is not
+        # essentially needed.  To re-enable it, please uncomment the following
+        # if-statement.
+        local mode=--
+        # if ((COMP_TYPE != 9 && COMP_TYPE != 37 && COMP_TYPE != 42)); then
+        #     mode=-d # display-only mode
+        # fi
 
-        COMPREPLY=( $( compgen -W "$( make -qp $makef $makef_dir 2>/dev/null | \
-            awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ \
-            {split($1,A,/ /);for(i in A)print A[i]}' )" \
-            -- "$cur" ) )
+        local IFS=$' \t\n' script=$(_make_target_extract_script $mode "$cur")
+        COMPREPLY=($(LC_ALL=C \
+            $1 -npq __BASH_MAKE_COMPLETION__=1 \
+            ${makef+"${makef[@]}"} "${makef_dir[@]}" .DEFAULT 2>/dev/null |
+            command sed -ne "$script"))
+
+        _comp_make__truncate_non_unique_paths
+
+        if [[ $mode != -d ]]; then
+            # Completion will occur if there is only one suggestion
+            # so set options for completion based on the first one
+            [[ ${COMPREPLY-} == */ ]] && compopt -o nospace
+        fi
 
     fi
 } &&
-complete -F _make make gmake gnumake pmake
+    complete -F _make make gmake gnumake pmake colormake bmake
 
-# Local variables:
-# mode: shell-script
-# sh-basic-offset: 4
-# sh-indent-comment: t
-# indent-tabs-mode: nil
-# End:
-# ex: ts=4 sw=4 et filetype=sh
+# ex: filetype=sh
